In [3]:
import numpy as np

def step_function(x):
    return np.where(x>=0,1,0)

X_and=np.array([[0,0],[0,1],[1,0],[1,1]])
y_and=np.array([[0],[0],[0],[1]])

X_or=np.array([[0,0],[0,1],[1,0],[1,1]])
y_or=np.array([[0],[1],[1],[1]])

class perceptron:
    def __init__(self,input_size,learning_rate=0.1,epochs=1000):
        self.weights=np.zeros((input_size,1))
        self.bias=0
        self.learning_rate=learning_rate
        self.epochs=epochs
    
    def train(self,X,y):
        for _ in range(self.epochs):
            for inputs,labels in zip(X,y):
                inputs=inputs.reshape(-1,1)
                linear_output=np.dot(inputs.T,self.weights)+self.bias
                prediction=step_function(linear_output)
                error=labels-prediction
                self.weights+=self.learning_rate*error*inputs
                self.bias+=self.learning_rate*error
                
    def predict(self,X):
        linear_output=np.dot(X,self.weights)+self.bias
        return step_function(linear_output)
    
    
perceptron_and=perceptron(input_size=2)
perceptron_and.train(X_and,y_and)

perceptron_or=perceptron(input_size=2)
perceptron_or.train(X_or,y_or)

print("perceptron and predictions")
print(perceptron_and.predict(X_and))

print("perceptron or predictions")
print(perceptron_or.predict(X_or))

perceptron and predictions
[[0]
 [0]
 [0]
 [1]]
perceptron or predictions
[[0]
 [1]
 [1]
 [1]]


In [6]:
import numpy as np

def step_function(x):
    return np.where(x>=0,1,0)


x_and=np.array([[0,0],[0,1],[1,0],[1,1]])
y_and=np.array([[0],[0],[0],[1]])

x_or=np.array([[0,0],[0,1],[1,0],[1,1]])
y_or=np.array([[0],[1],[1],[1]])


class perceptron:
    def __init__(self,input_size,learning_rate=0.5,epochs=100):
        self.weights=np.zeros((input_size,1))
        self.bias=0
        self.learning_rate=learning_rate
        self.epochs=epochs
        
    def train(self,X,y):
        for _ in range(self.epochs):
            for inputs,labels in zip(X,y):
                inputs=inputs.reshape(-1,1)
                linear_output=np.dot(inputs.T,self.weights)+self.bias
                predictions=step_function(linear_output)
                error=labels-predictions
                self.weights+=self.learning_rate*error*inputs
                self.bias+=self.learning_rate*error
                
    def predict(self,X):
        linear_output=np.dot(X,self.weights)+self.bias
        return step_function(linear_output)
    
perceptron_and=perceptron(input_size=2)
perceptron_and.train(x_and,y_and)

perceptron_or=perceptron(input_size=2)
perceptron_or.train(x_or,y_or)

print("and results:")
prediction=perceptron_and.predict(x_and)
print(prediction)

print("or results:")
print(perceptron_or.predict(x_or))
                


and results:
[[0]
 [0]
 [0]
 [1]]
or results:
[[0]
 [1]
 [1]
 [1]]
